# Generated by Django 4.2 on 2025-08-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='number',
            field=models.CharField(default=0, max_length=50, verbose_name='号码'),
        ),
    ]
