# Generated by Django 4.2 on 2025-08-14 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_teachers_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('number', models.CharField(max_length=50, verbose_name='学生电话')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.teachers', verbose_name='班主任')),
            ],
        ),
    ]
