# Generated by Django 4.2 on 2025-08-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='管理员姓名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
            ],
        ),
    ]
