# Generated by Django 4.2 on 2025-08-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='number',
            field=models.CharField(max_length=50, verbose_name='学号'),
        ),
    ]
